name: flame_worldgen
description: A procedural world generation toolkit for Flame, providing chunk-based tile management, animated and weighted sprites, and noise-driven terrain generation for 2D games.
version: 1.0.0
repository: https://github.com/bszarlej/flame_worldgen
issue_tracker: https://github.com/bszarlej/flame_worldgen/issues
topics:
  - flame
  - noise
  - game-development

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.30.1
  fast_noise: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=5.0.0 <7.0.0"
  test: ^1.25.15
