import 'dart:async';
import 'dart:collection';
import 'dart:ui';

import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flutter/foundation.dart';

import 'chunk.dart';
import 'collision/solid_tiles.dart';
import 'core/chunk_data.dart';
import 'core/coords.dart';
import 'core/generation/biome.dart';
import 'core/generation/scatter.dart';
import 'core/generation/world_generator.dart';
import 'core/noise/noise_field.dart';
import 'core/tile_palette.dart';
import 'core/tile_rects.dart';
import 'core/tile_type.dart';
import 'render/chunk_painter.dart';
import 'render/tile_sources.dart';
import 'render/tileset.dart';
import 'streaming/chunk_cache.dart';
import 'streaming/chunk_range.dart';
import 'streaming/chunk_streamer.dart';
import 'streaming/create_executor.dart';
import 'streaming/streaming_options.dart';

/// An infinite, seeded tile world that follows the camera.
///
/// ```dart
/// world.add(
///   ProceduralMap(
///     seed: 42,
///     generator: WorldGenerator(...),
///     tileset: Tileset(...),
///   ),
/// );
/// ```
///
/// Chunks are generated around the camera's visible area as it moves and
/// unloaded when they're far away. Generation runs on a worker isolate, or
/// on the web within a time budget per frame, so new chunks appear a few
/// frames after they come into range. Tile (0, 0) is drawn at the map's
/// origin, and each tile is [Tileset.tileSize] pixels.
///
/// Turn on [debugMode] to see chunk borders, chunk coordinates and scatter
/// spots.
class ProceduralMap extends Component with HasGameReference<FlameGame> {
  /// Creates a map of the world with [seed], generated by [generator] and
  /// drawn with [tileset].
  ///
  /// [chunkSize] is the number of tiles along each side of a chunk and must
  /// be a power of two. [camera] defaults to the game's camera.
  ///
  /// With [collision], solid tiles get hitboxes, see [SolidTiles]. Your game
  /// or world needs Flame's [HasCollisionDetection] mixin.
  ///
  /// The generator is sent to a worker isolate, so it must not reference
  /// anything that can't cross isolates, such as images or components.
  ProceduralMap({
    required this.seed,
    required this.generator,
    required this.tileset,
    int chunkSize = 32,
    StreamingOptions? streaming,
    this.collision = false,
    this.onChunkLoaded,
    this.onChunkUnloaded,
    CameraComponent? camera,
  }) : grid = ChunkGrid(chunkSize),
       streaming = streaming ??= StreamingOptions(),
       _camera = camera,
       _palette = ChunkGenerator.paletteFor(generator, tileset.tiles.keys),
       _chunkPixels = tileset.tileSize * chunkSize.toDouble(),
       _cache = ChunkCache(streaming.cacheSize);

  /// The world seed.
  final int seed;

  /// Decides which tile type goes where.
  final WorldGenerator generator;

  /// Decides how each tile type is drawn.
  final Tileset tileset;

  /// The size of the chunks.
  final ChunkGrid grid;

  /// How chunks are loaded and unloaded.
  final StreamingOptions streaming;

  /// Whether solid tiles get hitboxes. Each loaded chunk adds a [SolidTiles]
  /// child for every solid tile type in it.
  final bool collision;

  /// Called when a chunk is loaded, during [update] and before the chunk is
  /// first rendered.
  final void Function(Chunk chunk)? onChunkLoaded;

  /// Called when a chunk is unloaded, during [update] or when the map is
  /// removed.
  final void Function(Chunk chunk)? onChunkUnloaded;

  final CameraComponent? _camera;
  final TilePalette _palette;

  /// Whether each tile id is solid.
  late final List<bool> _solid = [
    for (final type in _palette.types) type.solid,
  ];
  late final TileSources _sources;
  late final ChunkPainter _painter;
  final _loaded = <ChunkCoord, _LoadedChunk>{};

  /// Chunks that aren't loaded, from the streamer and from queries.
  final ChunkCache _cache;

  /// Generates chunks for queries outside the loaded area, and evaluates
  /// fields for [valueAt].
  late final _queries = ChunkGenerator(
    generator,
    seed: seed,
    grid: grid,
    tiles: tileset.tiles.keys,
  );
  final _paint = Paint()..filterQuality = FilterQuality.none;

  /// Seconds since the map started, the clock of every tile animation.
  var _time = 0.0;

  /// The frame each animated tile id shows, indexed by tile id.
  late final List<int> _frames;

  /// Loads and unloads chunks. Null while the worker is starting and after
  /// the map is removed.
  ChunkStreamer? _streamer;
  Future<void>? _starting;

  /// Whether the map is loading or mounted, so a worker that finishes
  /// starting after the map is removed is stopped again.
  var _active = false;

  CameraComponent get _activeCamera => _camera ?? game.camera;

  /// Returns the tile under [position], in the map's coordinates.
  ///
  /// Works anywhere, even before the map is added to the game. If the tile's
  /// chunk isn't loaded, it's generated on the spot, which takes a
  /// millisecond or two, and kept in the cache so it's not generated twice.
  TileType tileAt(Vector2 position) => tileAtCoord(tileCoordAt(position));

  /// Returns the tile at [coord]. See [tileAt].
  TileType tileAtCoord(TileCoord coord) =>
      _palette[_chunkData(coord).tileIdAt(coord)];

  /// Returns the biome under [position], in the map's coordinates. See
  /// [tileAt].
  Biome biomeAt(Vector2 position) => biomeAtCoord(tileCoordAt(position));

  /// Returns the biome at [coord]. See [tileAt].
  Biome biomeAtCoord(TileCoord coord) =>
      generator.biomes[_chunkData(coord).biomeAt(coord)];

  /// Returns the value of [field] at [position], in the map's coordinates,
  /// between -1 and 1.
  ///
  /// The field is evaluated directly, so this works anywhere without
  /// generating a chunk, and changes smoothly as [position] moves. At the
  /// centre of a tile, it's the value the biome conditions saw.
  ///
  /// Throws if [field] isn't one of the generator's fields.
  double valueAt(NoiseField field, Vector2 position) {
    final tile = tileset.tileSize;
    return _queries.valueAt(
      field,
      position.x / tile.x - 0.5,
      position.y / tile.y - 0.5,
    );
  }

  /// Returns the tile under [position], in the map's coordinates.
  TileCoord tileCoordAt(Vector2 position) {
    final tile = tileset.tileSize;
    return TileCoord(
      (position.x / tile.x).floor(),
      (position.y / tile.y).floor(),
    );
  }

  /// Returns the top-left corner of [coord], in the map's coordinates.
  Vector2 positionOf(TileCoord coord) {
    final tile = tileset.tileSize;
    return Vector2(coord.x * tile.x, coord.y * tile.y);
  }

  /// The chunk that holds [tile]: loaded, cached, or generated now.
  ChunkData _chunkData(TileCoord tile) {
    final coord = grid.chunkOf(tile);
    final loaded = _loaded[coord];
    if (loaded != null) return loaded.data;
    final cached = _cache.get(coord);
    if (cached != null) return cached;
    final chunk = _queries.generate(coord);
    _cache.put(chunk);
    return chunk;
  }

  /// The chunks currently loaded.
  @visibleForTesting
  Iterable<ChunkCoord> get loadedChunks => _loaded.keys;

  /// Whether every chunk the last [update] wanted is loaded. False while the
  /// worker is starting.
  @visibleForTesting
  bool get isSettled => _streamer?.inFlight == 0;

  /// The part of the tileset's atlas drawn for [tile], which must be in a
  /// loaded chunk. Only for tilesets without transitions, where each tile is
  /// one sprite.
  @visibleForTesting
  Rect sourceRectAt(TileCoord tile) {
    assert(_painter.dualGrid == null, 'tiles are drawn in a dual grid');
    return paintedChunk(
      grid.chunkOf(tile),
    )!.mesh.sourceAt(grid.localIndex(tile));
  }

  /// The sprites of the chunk at [coord], or null if it isn't loaded.
  @visibleForTesting
  PaintedChunk? paintedChunk(ChunkCoord coord) => _loaded[coord]?.painted;

  /// The size of one chunk, in pixels.
  final Vector2 _chunkPixels;

  @override
  Future<void> onLoad() async {
    _active = true;
    assert(
      !collision || findParent<HasCollisionDetection>() != null,
      'ProceduralMap(collision: true) needs HasCollisionDetection on the '
      'game or the world. Without it, the hitboxes never collide.',
    );
    _sources = tileset.sources(_palette, seed: seed);
    _painter = ChunkPainter(
      grid: grid,
      tileWidth: tileset.tileSize.x,
      tileHeight: tileset.tileSize.y,
      sources: _sources,
      dualGrid: tileset.dualGrid(_palette),
    );
    _frames = [
      for (var id = 0; id < _sources.length; id++)
        _sources.isAnimated(id) ? _sources.frameAt(id, _time) : -1,
    ];
    await _startStreaming();
  }

  @override
  void onMount() {
    _active = true;
    // The map was removed and added again.
    if (_streamer == null) unawaited(_startStreaming());
  }

  @override
  void onRemove() {
    _active = false;
    _streamer?.dispose();
    _streamer = null;
  }

  Future<void> _startStreaming() => _starting ??= () async {
    try {
      final executor = await createExecutor(
        generator,
        seed: seed,
        grid: grid,
        tiles: tileset.tiles.keys,
        frameBudget: streaming.frameBudget,
      );
      if (!_active || _streamer != null) {
        executor.dispose();
        return;
      }
      _streamer = ChunkStreamer(
        executor: executor,
        options: streaming,
        cache: _cache,
        onLoaded: _load,
        onUnloaded: _unload,
      );
    } finally {
      _starting = null;
    }
  }();

  @override
  void update(double dt) {
    _time += dt;
    _animate();

    final streamer = _streamer;
    final visible = _activeCamera.visibleWorldRect;
    if (streamer == null || visible.isEmpty) return;
    streamer.update(_visibleChunks(visible));
  }

  @override
  void render(Canvas canvas) {
    final visible = _activeCamera.visibleWorldRect;
    for (final chunk in _loaded.values) {
      final painted = chunk.painted;
      if (painted.bounds.overlaps(visible)) {
        painted.mesh.render(canvas, tileset.atlas, _paint);
      }
    }
  }

  @override
  void renderDebugMode(Canvas canvas) {
    final border = Paint()
      ..style = PaintingStyle.stroke
      ..strokeWidth = 1
      ..color = debugColor;
    final spot = Paint()..color = debugColor;
    final tile = tileset.tileSize;
    final spotRadius = tile.x / 4;

    for (final MapEntry(key: coord, value: chunk) in _loaded.entries) {
      canvas.drawRect(chunk.bounds, border);
      debugTextPaint.render(
        canvas,
        '${coord.x}, ${coord.y}',
        Vector2(chunk.bounds.left + 4, chunk.bounds.top + 4),
      );
      for (final s in chunk.data.spots) {
        canvas.drawCircle(Offset(s.x * tile.x, s.y * tile.y), spotRadius, spot);
      }
    }
  }

  /// Shows the current frame of every animation whose frame changed.
  void _animate() {
    for (final id in _sources.animatedIds) {
      final frame = _sources.frameAt(id, _time);
      if (frame == _frames[id]) continue;
      _frames[id] = frame;
      final source = _sources.frameRect(id, frame);
      for (final chunk in _loaded.values) {
        chunk.painted.showFrame(id, source);
      }
    }
  }

  void _load(ChunkData data) {
    final tile = tileset.tileSize;
    final origin = data.origin;
    final chunk = _LoadedChunk(
      data,
      _palette,
      generator.biomes,
      _painter.paint(data, _tileIdAt, _time),
      Rect.fromLTWH(
        origin.x * tile.x,
        origin.y * tile.y,
        _chunkPixels.x,
        _chunkPixels.y,
      ),
    );
    _loaded[data.coord] = chunk;
    if (collision) {
      chunk.solids = _solidTiles(data);
      addAll(chunk.solids);
    }

    // In a dual grid, the chunks right of and below this one draw some of
    // its tiles. Until now, they used their own edge tiles in their place.
    if (_painter.dualGrid != null) {
      for (final (dx, dy) in const [(1, 0), (0, 1), (1, 1)]) {
        final neighbour = _loaded[data.coord.translate(dx, dy)];
        neighbour?.painted = _painter.paint(neighbour.data, _tileIdAt, _time);
      }
    }
    onChunkLoaded?.call(chunk);
  }

  /// The tile id at ([x], [y]), or null if its chunk isn't loaded.
  int? _tileIdAt(int x, int y) {
    final tile = TileCoord(x, y);
    final chunk = _loaded[grid.chunkOf(tile)];
    return chunk?.data.tiles[grid.localIndex(tile)];
  }

  void _unload(ChunkData data) {
    final chunk = _loaded.remove(data.coord);
    if (chunk == null) return;
    removeAll(chunk.solids);
    onChunkUnloaded?.call(chunk);
  }

  /// The hitboxes of the solid tiles in [data], one component per tile type.
  List<SolidTiles> _solidTiles(ChunkData data) {
    final tile = tileset.tileSize;
    final origin = data.origin;
    return [
      for (final MapEntry(key: id, value: rects) in mergeTiles(
        data,
        (id) => _solid[id],
      ).entries)
        SolidTiles(
          type: _palette[id],
          chunk: data.coord,
          position: Vector2(origin.x * tile.x, origin.y * tile.y),
          size: _chunkPixels.clone(),
          rects: [
            for (final rect in rects)
              Rect.fromLTWH(
                rect.x * tile.x,
                rect.y * tile.y,
                rect.width * tile.x,
                rect.height * tile.y,
              ),
          ],
        ),
    ];
  }

  /// The chunks that [visible] overlaps.
  ChunkRange _visibleChunks(Rect visible) {
    final pixels = _chunkPixels;
    return ChunkRange(
      (visible.left / pixels.x).floor(),
      (visible.top / pixels.y).floor(),
      (visible.right / pixels.x).floor(),
      (visible.bottom / pixels.y).floor(),
    );
  }
}

class _LoadedChunk implements Chunk {
  _LoadedChunk(
    this.data,
    this._palette,
    this._biomes,
    this.painted,
    this.bounds,
  );

  final ChunkData data;
  final TilePalette _palette;
  final List<Biome> _biomes;

  /// The chunk's sprites. Painted again when a neighbour loads.
  PaintedChunk painted;

  /// The chunk's hitboxes, if the map has collision.
  List<SolidTiles> solids = const [];

  @override
  final Rect bounds;

  @override
  ChunkCoord get coord => data.coord;

  @override
  Iterable<TileCoord> get coords => data.coords;

  @override
  bool contains(TileCoord tile) => data.contains(tile);

  @override
  TileType tileAt(TileCoord tile) => _palette[data.tileIdAt(tile)];

  @override
  Biome biomeAt(TileCoord tile) => _biomes[data.biomeAt(tile)];

  @override
  List<ScatterSpot> get spots => UnmodifiableListView(data.spots);

  @override
  String toString() => 'Chunk($coord)';
}
