import 'dart:ui';

import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flame/sprite.dart';
import 'package:flutter/foundation.dart';

import 'core/chunk_data.dart';
import 'core/coords.dart';
import 'core/generation/world_generator.dart';
import 'render/tileset.dart';

/// An infinite, seeded tile world that follows the camera.
///
/// ```dart
/// world.add(
///   ProceduralMap(
///     seed: 42,
///     generator: WorldGenerator(...),
///     tileset: Tileset(...),
///   ),
/// );
/// ```
///
/// Chunks are generated around the camera's visible area as it moves and
/// dropped when they're far away. Tile (0, 0) is drawn at the map's origin,
/// and each tile is [Tileset.tileSize] pixels.
///
/// Turn on [debugMode] to see chunk borders, chunk coordinates and scatter
/// spots.
class ProceduralMap extends Component with HasGameReference<FlameGame> {
  /// Creates a map of the world with [seed], generated by [generator] and
  /// drawn with [tileset].
  ///
  /// [chunkSize] is the number of tiles along each side of a chunk and must
  /// be a power of two. [camera] defaults to the game's camera.
  ProceduralMap({
    required this.seed,
    required this.generator,
    required this.tileset,
    int chunkSize = 32,
    CameraComponent? camera,
  }) : grid = ChunkGrid(chunkSize),
       _camera = camera;

  /// The world seed.
  final int seed;

  /// Decides which tile type goes where.
  final WorldGenerator generator;

  /// Decides how each tile type is drawn.
  final Tileset tileset;

  /// The size of the chunks.
  final ChunkGrid grid;

  /// Chunks loaded beyond the visible area, in every direction.
  static const _loadMargin = 1;

  /// Chunks kept beyond the visible area before they're dropped. Larger than
  /// [_loadMargin], so moving back and forth over a chunk border doesn't
  /// generate the same chunks again and again.
  static const _unloadMargin = 2;

  final CameraComponent? _camera;
  late final ChunkGenerator _chunks;
  late final List<Rect> _sourceRects;
  final _loaded = <ChunkCoord, _LoadedChunk>{};
  final _paint = Paint()..filterQuality = FilterQuality.none;

  CameraComponent get _activeCamera => _camera ?? game.camera;

  /// The chunks currently loaded.
  @visibleForTesting
  Iterable<ChunkCoord> get loadedChunks => _loaded.keys;

  /// The size of one chunk, in pixels.
  late final Vector2 _chunkPixels;

  @override
  Future<void> onLoad() async {
    _chunks = ChunkGenerator(
      generator,
      seed: seed,
      grid: grid,
      tiles: tileset.tiles.keys,
    );
    _sourceRects = tileset.sourceRects(_chunks.palette);
    _chunkPixels = tileset.tileSize * grid.size.toDouble();
  }

  @override
  void update(double dt) {
    final visible = _activeCamera.visibleWorldRect;
    if (visible.isEmpty) return;

    final load = _chunkRange(visible, _loadMargin);
    final keep = _chunkRange(visible, _unloadMargin);

    _loaded.removeWhere((coord, _) => !keep.contains(coord));
    for (final coord in load.coords) {
      _loaded.putIfAbsent(coord, () => _load(coord));
    }
  }

  @override
  void render(Canvas canvas) {
    final visible = _activeCamera.visibleWorldRect;
    for (final chunk in _loaded.values) {
      if (chunk.bounds.overlaps(visible)) {
        chunk.batch.render(canvas, paint: _paint);
      }
    }
  }

  @override
  void renderDebugMode(Canvas canvas) {
    final border = Paint()
      ..style = PaintingStyle.stroke
      ..strokeWidth = 1
      ..color = debugColor;
    final spot = Paint()..color = debugColor;
    final tile = tileset.tileSize;
    final spotRadius = tile.x / 4;

    for (final MapEntry(key: coord, value: chunk) in _loaded.entries) {
      canvas.drawRect(chunk.bounds, border);
      debugTextPaint.render(
        canvas,
        '${coord.x}, ${coord.y}',
        Vector2(chunk.bounds.left + 4, chunk.bounds.top + 4),
      );
      for (final s in chunk.data.spots) {
        canvas.drawCircle(Offset(s.x * tile.x, s.y * tile.y), spotRadius, spot);
      }
    }
  }

  _LoadedChunk _load(ChunkCoord coord) {
    final data = _chunks.generate(coord);
    final tile = tileset.tileSize;
    final origin = data.origin;
    final batch = SpriteBatch(tileset.atlas);
    for (var index = 0; index < grid.area; index++) {
      final x = origin.x + index % grid.size;
      final y = origin.y + index ~/ grid.size;
      batch.addTransform(
        source: _sourceRects[data.tiles[index]],
        transform: RSTransform(1, 0, x * tile.x, y * tile.y),
      );
    }
    return _LoadedChunk(
      data,
      batch,
      Rect.fromLTWH(
        origin.x * tile.x,
        origin.y * tile.y,
        _chunkPixels.x,
        _chunkPixels.y,
      ),
    );
  }

  /// The chunks that [visible] overlaps, plus [margin] chunks on each side.
  _ChunkRange _chunkRange(Rect visible, int margin) {
    final pixels = _chunkPixels;
    return _ChunkRange(
      (visible.left / pixels.x).floor() - margin,
      (visible.top / pixels.y).floor() - margin,
      (visible.right / pixels.x).floor() + margin,
      (visible.bottom / pixels.y).floor() + margin,
    );
  }
}

class _LoadedChunk {
  _LoadedChunk(this.data, this.batch, this.bounds);

  final ChunkData data;
  final SpriteBatch batch;

  /// Where the chunk is in the world, in pixels.
  final Rect bounds;
}

/// An inclusive rectangle of chunk coordinates.
class _ChunkRange {
  const _ChunkRange(this.left, this.top, this.right, this.bottom);

  final int left;
  final int top;
  final int right;
  final int bottom;

  bool contains(ChunkCoord coord) =>
      coord.x >= left &&
      coord.x <= right &&
      coord.y >= top &&
      coord.y <= bottom;

  Iterable<ChunkCoord> get coords sync* {
    for (var y = top; y <= bottom; y++) {
      for (var x = left; x <= right; x++) {
        yield ChunkCoord(x, y);
      }
    }
  }
}
