name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    uses: ./.github/workflows/ci.yaml
  
  dry-run:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart pub publish --dry-run

  publish:
    needs: [test, dry-run]
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    permissions:
      id-token: write
    with:
      working-directory: .
